<a href="https://colab.research.google.com/github/Harshabobbiti626/Machine-Learning-Techniques/blob/main/KNN_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#KNN Algorithm#

The k-nearest neighbors (KNN) algorithm is a supervised machine learning algorithm that is used for classification and regression. In the KNN algorithm, the basic idea is to predict the target variable of a new data point based on the values of the nearest k data points in the training set.

**KNN working:**

Determine the number of nearest neighbors, k, that will be used to make the prediction.

Calculate the distance between the new data point and all the data points in the training set.

Select the k nearest neighbors based on their distance from the new data point.

For classification problems, the most common class among the k nearest neighbors is assigned to the new data point. For regression problems, the average or the mean of the values of the k nearest neighbors is used to make the prediction.

The KNN algorithm is simple and easy to implement, but it requires a large amount of memory to store the entire training set. It is also sensitive to the choice of k, so choosing an appropriate value for k is an important step in the implementation of the KNN algorithm.

In [6]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
headernames = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Class']

In [15]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Machine Learning datasets/iris.data', names = headernames)
dataset.head()

In [16]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values

KNeighborsRegressor(n_neighbors=10)

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.40)

In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [23]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8)
classifier.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [13]:
y_pred = classifier.predict(X_test)

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[14  0  0]
 [ 0 21  1]
 [ 0  2 22]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       0.91      0.95      0.93        22
 Iris-virginica       0.96      0.92      0.94        24

       accuracy                           0.95        60
      macro avg       0.96      0.96      0.96        60
   weighted avg       0.95      0.95      0.95        60

Accuracy: 0.95
